### ISSUE TITLE
Hello guys

### ISSUE THREAD

**Issue by Henrycobaltech** [ZA-PT/Test#1]
here is a test

**Comment by Henrycobaltech** [comment]
@SamLangTen hey guy

**Comment by Henrycobaltech** [comment]
@allenlooplee hello here

**Comment by allenlooplee** [comment]
How about a reply to the group directly?

发送自 Outlook




On Thu, Feb 26, 2015 at 9:30 PM -0800, "Henry Charles" <notifications@github.com> wrote:
here is a test

---
Reply to this email directly or view it on GitHub:
https://github.com/ZA-Power-Team/Test/issues/1

**Comment by Henrycobaltech** [comment]
it works
